disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "mdoradom"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "// Creating games. Based in Barcelona. Pro FOSS 💙"

[params.author]
name = "Mario"
bio = "Test author description"
headline = "// Creating games. Based in Barcelona. Pro FOSS 💙"
image = "profile.png"
links = [
	{ github = "https://github.com/mdoradom" },
	{ linkedin = "https://linkedin.com/in/mario-dorado-martinez" },
	{ mastodon = "https://mastodon.social/@mdoradom" },
	{ itch-io = "https://mdoradom.itch.io" },
	{ email = "mailto:mariodoradomartinez@gmail.com" }
]
